services:
  back:
    build: ../backend
    container_name: back
    command: ["npm", "run", "start:e2e"]
    volumes:
      - ./database:/app/database
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://back:9428/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 3s

  front:
    build:
      context: ../front-end
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: docker-e2e
    container_name: front
    healthcheck:
      test: ["CMD", "curl", "-f", "http://front:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - my_network
    depends_on:
      back:
        condition: service_healthy
  
  playwright:
    build:
      context: ../front-end
      dockerfile: Dockerfile-e2e
    container_name: playwright
    networks:
      - my_network
    volumes:
      - ./test_results:/app/test-results
    depends_on:
      front:
        condition: service_healthy

volumes:
  my_volume:
  test_results:

networks:
  my_network: