services:
  back:
    build: ../backend
    container_name: back
    volumes:
      - ./database:/app/database
    ports:
      - "8081:9428"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://back:9428/api/status"]
      interval: 10s
      timeout: 10s
      retries: 3

  front:
    build:
      context: ../front-end
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: docker
    container_name: front
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://front:80/"]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      back:
        condition: service_healthy

volumes:
  database:
    driver: local